### ISSUE TITLE
Chores tracking issue

### ISSUE THREAD

**Issue by Baptistemontan** [Baptistemontan/leptos_i18n#109]
This is an issue to track chores, those include things like improving CI, updating docs, some refactoring. 

Anything that doesn't impact the  user side of the library, so no beahvior changes.

- [ ] Update macros output doc
- [ ] Add macros tests with [`trybuild`](https://github.com/dtolnay/trybuild)
- [ ] More robust e2e tests
- [ ] More tests in general
