### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Baptistemontan** [Baptistemontan/leptos_i18n#112]
# v0.3 

I prefer working on v0.4 with possible small breaking changes

# v0.4

Focus on adding needed small needed features, fixing some bugs and close as much issues as possible

### Todo:

- [x] fix bug with `debug_interpolations` #102
- [x] Only show keys feature #102  
- [x] Fix `csr` locale resolution #108
- [x] Better locale matching algorithm (shamefully stolen from `fluent-template`) done in #107
- [x] Scoped contexts #111 
- [x] Routing #113 
- [ ] Subcontexts #114 
- [ ] Use the [`typed-builder`](https://github.com/idanarye/rust-typed-builder) crate for interpolation
- [ ] Update all docs

# v0.5

Only focus is dynamic loading of translations

### Todo:

- [ ] Dynamic loading of translations #88 

# v0.6

Port the lib to Leptos v0.7

### Todo:

- [ ] Update to Leptos v0.7

**Comment by Baptistemontan** [comment]
Moved this issue to [v0.4 milestone](https://github.com/Baptistemontan/leptos_i18n/milestone/1)
